server:
  port: ${PORT:0}

spring:
  application:
    name: products-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eda_cqrs_axon_products
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    

#axon:
#  serializer:
#    general: jackson
#    events: jackson
#    messages: jackson
